Wip/clean front
WildCodeSchool/2104-wns-remote-alphas pull request #121
Opened 2022-02-20 05:04 UTC by Elya29

For authentication and homepage :
- fix accessibility concerns
- fix design
- break the responsive (wip)
- add pandatips (wip)
- add keyboard navigation
- add screen reader compatibility

To be continued...

2022-02-20 20:47 UTC, TheodoreLefrancois commented
Pourquoi tu as enlevé le typage des requetes graphql en front ?

2022-02-20 20:53 UTC, TheodoreLefrancois requested changes
Bien joué beau boulot  🔥  par contre je t'ai laissé deux commentaires ... si tu veux y répondre ? 😉

2022-02-20 20:53 UTC, TheodoreLefrancois commented on front/src/Router.tsx
> +											{user?.role === 'admin' && (
pourquoi tu as remis 'admin' en dur alors que l'on utilisait l'enum ?

2022-02-20 20:56 UTC, Elya29 commented on front/src/Router.tsx
> +											{user?.role === 'admin' && (
j'ai rien changé, je suis partie de dev. Tu l'as merge?

2022-02-20 20:57 UTC, Elya29 commented
> Pourquoi tu as enlevé le typage des requetes graphql en front ?

rien changé non plus, j'ai pas touché à ça.

2022-02-21 02:22 UTC, Elya29 commented
Accessibilité ok sur la landing page, sign in, sign up, la home, le back office et la timeline (tests Wave + navigation au clavier). J'ai ajouté un lien "skip to content" quand on navigue au clavier, pour ne pas avoir à tab le menu à chaque fois.

Le responsive est ok sur la landing page, sign in, sign up et la home. Y'a encore du boulot mais ça avance !

2022-02-22 09:06 UTC, Elya29 commented
@TheodoreLefrancois c'est bon j'ai fix le bug avec les enums et les types, tu check si j'ai rien oublié? merci :)

2022-02-23 10:25 UTC, TheodoreLefrancois approved these changes
Magnifique 🔥 , j'approuve et je merge ça de suite

2022-02-23 10:25 UTC, merged